// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfkmdbuffehsgmoznhae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRma21kYnVmZmVoc2dtb3puaGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNTMwMDUsImV4cCI6MjA3NjYyOTAwNX0.IfwDhRRnbth4sjNqedsBNEt8tu9Ppnxo0vowIkKzkbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});